name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: windows-latest 
    strategy:
      matrix:
        configuration: [Debug, Release] 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet .\project-cs.sln build --configuration Debug
    - name: Build
      run: dotnet .\project-cs.sln build --configuration Release
